canna_cross/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'canna_cross'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='canna_cross.html'), name='cross'),
    url(r'list/(\w+)/$', views.company, name="list"),
]

encyclopedia/urls.py
from django.conf.urls import url

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'strains/$', views.StrainListView.as_view(), name="strain-list"),
    url(r'history/$', views.HistoryListView.as_view(), name='history'),
    url(r'cups/$', views.CupListView.as_view(), name='cups'),
    url(r'seed-banks/$', views.SeedBankListView.as_view(), name='seed_banks'),
    url(r'strains/(?P<webId>[0-9]+)/$', views.StrainDeatailView.as_view(), name="strain"),
    url(r'history/(?P<pk>[0-9]+)/$', views.HistoryDetailView.as_view(), name="history_detail"),
    url(r'cup/(?P<pk>[0-9]+)/$', views.CupDetailView.as_view(), name="cup_detail"),
    url(r'seed-bank/(?P<pk>[0-9]+)/$', views.SeedBankDetailView.as_view(), name="seed_bank"),
    url(r'seed-banks/$', views.SeedBankListView.as_view(), name="seed_banks")
]

enofca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('encyclopedia.urls', namespace="encyclopedia")),
    url(r'^canna_cross/', include('canna_cross.urls', namespace="canna_cross")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^order/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^$', views.OrderView.as_view(), name='order'),
    url(r'success/$', TemplateView.as_view(template_name='success.html'), name='success'),
]

encyclopedia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.

class Strain(models.Model):
    name = models.CharField(u'název', max_length=100)
    info = models.TextField(u'informace', blank=True)
    bank = models.ForeignKey('SeedBank', on_delete=models.SET_NULL, null=True, blank=True)
    cup = models.ManyToManyField('Cup', blank=True)
    cup_place = models.PositiveSmallIntegerField(blank=True, null=True, default=None)
    webId = models.SlugField(max_length=50, unique=True)
    link = models.URLField(blank=True, null=True)

    #medical
    stress = models.PositiveSmallIntegerField(blank=True, default=0)
    insomnia = models.PositiveSmallIntegerField(blank=True, default=0)
    pain = models.PositiveSmallIntegerField(blank=True, default=0)
    depression = models.PositiveSmallIntegerField(blank=True, default=0)
    headaches = models.PositiveSmallIntegerField(blank=True, default=0)
    lack_of_appetite = models.PositiveSmallIntegerField(blank=True, default=0)
    muscle_spams = models.PositiveSmallIntegerField(blank=True, default=0)
    nausea = models.PositiveSmallIntegerField(blank=True, default=0)
    cramps = models.PositiveSmallIntegerField(blank=True, default=0)
    fatigue = models.PositiveSmallIntegerField(blank=True, default=0)
    inflammation = models.PositiveSmallIntegerField(blank=True, default=0)

    #effects
    communicative = models.PositiveSmallIntegerField(blank=True, default=0)
    creative = models.PositiveSmallIntegerField(blank=True, default=0)
    energetic = models.PositiveSmallIntegerField(blank=True, default=0)
    euphoric = models.PositiveSmallIntegerField(blank=True, default=0)
    focused = models.PositiveSmallIntegerField(blank=True, default=0)
    happy = models.PositiveSmallIntegerField(blank=True, default=0)
    relaxed = models.PositiveSmallIntegerField(blank=True, default=0)
    uplifted = models.PositiveSmallIntegerField(blank=True, default=0)
    talkative = models.PositiveSmallIntegerField(blank=True, default=0)
    aroused = models.PositiveSmallIntegerField(blank=True, default=0)
    giggly = models.PositiveSmallIntegerField(blank=True, default=0)

    #negatives
    dry_eyes = models.PositiveSmallIntegerField(blank=True, default=0)
    dry_mouth = models.PositiveSmallIntegerField(blank=True, default=0)
    headache = models.PositiveSmallIntegerField(blank=True, default=0)
    paranoid = models.PositiveSmallIntegerField(blank=True, default=0)
    dizzy = models.PositiveSmallIntegerField(blank=True, default=0)
    anxious = models.PositiveSmallIntegerField(blank=True, default=0)


    def __str__(self):
        return '{} - {}'.format(self.name, self.webId)

def seed_bank_upload(instance, filename):
    return 'banks/{0}/{1}'.format(instance.name, filename)

class SeedBank(models.Model):
    logo = models.ImageField(upload_to=seed_bank_upload, blank=True, null=True)
    name = models.CharField(max_length=100)
    link = models.URLField(blank=True, null=True)
    info = models.TextField(u'informace', blank=True)

    def __str__(self):
        return '{}'.format(self.name)

#odstarnit poté z migrací
def revard_upload(instance, filename):
    return 'revards/{0}/{1}'.format(instance.name, filename)

def cup_upload(instance, filename):
    return 'cups/{0}/{1}'.format(instance.cup.name, filename)

class Revadr(models.Model):
    pass

class Cup(models.Model):
    name = models.CharField(max_length=100)
    info = models.TextField(u'informace', blank=True)

    def __str__(self):
        return '{}'.format(self.name)

class CupPhoto(models.Model):
    cup = models.ForeignKey('Cup', on_delete=models.SET_NULL, null=True, blank=True)
    logo = models.ImageField(upload_to=cup_upload, blank=True, null=True)
    for_place = models.PositiveSmallIntegerField(blank=True, default=0)

def strain_directory_upload(instance, filename):
    return 'strains/{0}/{1}'.format(instance.strain.name, filename)

class StrainPhoto(models.Model):
    photo = models.ImageField(upload_to=strain_directory_upload)
    strain = models.ForeignKey('Strain', on_delete=models.SET_NULL, null=True, blank=True)

HISTORY_CHOICES = (
    ('1900', 'before 1900'),
    ('2000', '1900 - 2000'),
    ('now', '2000 - now'),
)

def history_upload_to(instance, filename):
    return 'history/{0}/{1}'.format(instance.period, filename)

class History(models.Model):
    period = models.CharField(max_length=10, choices = HISTORY_CHOICES)
    header = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to=history_upload_to, blank=True, null=True)
    pdf = models.FileField(upload_to=history_upload_to, blank=True, null=True)
    standing = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{} - {}'.format(self.period, self.header)

def person_upload_to(instance, filename):
    return 'person/{0}/{1}'.format(instance.id, filename)

class Person(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to=person_upload_to, blank=True, null=True)
    pdf = models.FileField(upload_to=history_upload_to, blank=True, null=True)
    standing = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{}'.format(self.name)

orders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail

STATUS_CHOICES = (
    (1, 'new'),
    (2, 'confirmed'),
    (4, 'payed'),
    (5, 'sended')
)

class Order(models.Model):
    quantity = models.PositiveSmallIntegerField(default=1)
    client = models.ForeignKey('clients.Client', on_delete=models.PROTECT)
    address = models.ForeignKey('clients.Address', on_delete=models.PROTECT)
    agree = models.BooleanField('I read and agree')
    status = models.PositiveSmallIntegerField(default=1, choices=STATUS_CHOICES)

    def __str__(self):
        return 'Order: {}'.format(self.pk)

orders/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.core.exceptions import ValidationError
from .models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ['status', 'client', 'address']

    def clean_agree(self):
        agree = self.cleaned_data['agree']
        if not agree:
            raise ValidationError('This field is required')

        return agree

encyclopedia/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView

from .models import Strain, StrainPhoto, History, HISTORY_CHOICES, CupPhoto, Cup, SeedBank
import pydash

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class StrainListView(ListView):
    model = Strain

    def get_context_data(self, **kwargs):
        strains = Strain.objects.order_by('name').values('name', 'webId')
        strains = pydash.group_by(strains, lambda strain: strain['name'][0].lower() if strain['name'][0].isalpha() else '#')
        kwargs['strains'] = sorted(strains.items())
        return super(StrainListView, self).get_context_data(**kwargs)

class StrainDeatailView(DetailView):
    model = Strain
    slug_field = "webId"
    slug_url_kwarg = "webId"
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super(StrainDeatailView, self).get_context_data(**kwargs)
        strain = self.get_object()
        context['photos'] = StrainPhoto.objects.filter(strain=strain)
        context['cups'] = CupPhoto.objects.filter(cup__in=strain.cup.all(), for_place=strain.cup_place)
        return context

class HistoryListView(ListView):
    model = History

    def get_context_data(self, **kwargs):
        historys = History.objects.order_by('standing')
        kwargs['historys'] = pydash.group_by(historys, lambda history: history.get_period_display())
        return super(HistoryListView, self).get_context_data(**kwargs)

class HistoryDetailView(DetailView):
    model = History

class CupListView(ListView):
    model = Cup

    def get_queryset(self):
        return Cup.objects.all().order_by('name')

class CupDetailView(DetailView):
    model = Cup

class SeedBankListView(ListView):
    model = SeedBank

    def get_queryset(self):
        return SeedBank.objects.all().order_by('name')

class SeedBankDetailView(DetailView):
    model = SeedBank

orders/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, render_to_response
from django.views.generic.edit import FormView, CreateView
from django.urls import reverse_lazy, reverse
from django.views.generic.base import View, TemplateResponseMixin
from django.views.generic.edit import FormMixin, ProcessFormView
from django.http import HttpResponseRedirect
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from orders.forms import OrderForm
from orders.models import Order
from clients.forms import AddressForm, ClientForm


class MultipleFormsMixin(FormMixin):
    """
    A mixin that provides a way to show and handle several forms in a
    request.
    """
    form_classes = {} # set the form classes as a mapping

    def get_form_classes(self):
        return self.form_classes

    def get_forms(self, form_classes):
        return dict([(key, klass(**self.get_form_kwargs())) for key, klass in form_classes.items()])

    def forms_valid(self, forms):
        return super(MultipleFormsMixin, self).form_valid(forms)

    def forms_invalid(self, forms):
        return self.render_to_response(self.get_context_data(forms=forms))


class ProcessMultipleFormsView(ProcessFormView):
    """
    A mixin that processes multiple forms on POST. Every form must be
    valid.
    """
    def get(self, request, *args, **kwargs):
        form_classes = self.get_form_classes()
        forms = self.get_forms(form_classes)
        return self.render_to_response(self.get_context_data(forms=forms))

    def post(self, request, *args, **kwargs):
        form_classes = self.get_form_classes()
        forms = self.get_forms(form_classes)
        if all([form.is_valid() for form in
            forms.values()]):
            return self.forms_valid(forms)
        else:
            return self.forms_invalid(forms)


class BaseMultipleFormsView(MultipleFormsMixin, ProcessMultipleFormsView):
    """
    A base view for displaying several forms.
    """

class MultipleFormsView(TemplateResponseMixin, BaseMultipleFormsView):
    """
    A view for displaing several forms, and rendering a template response.
    """
def send_order_email(order_id, to_email):
    subject = 'Order form ENOFCA ({})'.format(order_id)
    html_template = render_to_string('order_mail.html', {'order': order_id})
    plain_message = strip_tags(html_template)
    from_email = 'eshop@enofca.com'
    mail.send_mail(subject, plain_message, from_email, [to_email], html_message=html_template)

def send_info_email(order, client, address):
    subject = 'Order form ENOFCA ({})'.format(order.id)
    html_template = render_to_string('order_info_mail.html', {'order': order,
                                                         'client': client,
                                                         'address': address})
    plain_message = strip_tags(html_template)
    from_email = 'eshop@enofca.com'
    mail.send_mail(subject, plain_message, from_email, ['info@enofca.com'], html_message=html_template)

class OrderView(MultipleFormsView):
    template_name = 'order.html'
    success_url = reverse_lazy('orders:success')
    form_class=OrderForm
    form_classes = {
        'orderForm': OrderForm,
        'clientForm': ClientForm,
        'addressForm': AddressForm,
    }

    def post(self, request, *args, **kwargs):
        super(OrderView, self).post(request, *args, **kwargs)
        form_classes = self.get_form_classes()
        forms = self.get_forms(form_classes)
        client_form = forms.get('clientForm')
        address_form = forms.get('addressForm')
        order_form = forms.get('orderForm')
        if client_form.is_valid() and address_form.is_valid() and order_form.is_valid():
            client = client_form.save()
            client.save()
            address = address_form.save()
            address.save()
            order = Order.objects.create(
                quantity = order_form.cleaned_data['quantity'],
                agree = order_form.cleaned_data['agree'],
                client = client,
                address = address
            )
            order.save()
            send_order_email(order.id, client.email)
            send_info_email(order, client, address)
            return HttpResponseRedirect(reverse('orders:success'))
        return render(request, self.template_name, {
            'forms': forms
        })

encyclopedia/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<html class="computer" lang="en">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#56D25B",
      "text": "#ffffff"
    },
    "button": {
      "background": "#3CF"
    }
  },
  "showLink": false,
  "theme": "edgeless",
  "position": "bottom-right"
})});
</script>

<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121633073-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121633073-1');
</script>
<title>Encyclopedia of Cannabis</title>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="description" content="This is ENCYCLOPEDIA of CANNABIS. Looks like a common book. But tell me. Where you can find more than 1100 variety seeds from all the world? Information from more than 70 seed banks. Final product photos, effects, user ratings, genetics, price and much more." />
<meta name="keywords" content="Encyclopedia of Cannabis, cannabis, weed seeds, marijuana, medical marijuana, medical weed, Amsterdam weed, encyclopedia, marijuana seeds"
<meta name="revisit-after" content="7 days" />
<meta name="robots" content="all" />
<meta name="Copyright" content="Encyclopedia of Cannabis">
<meta name="author" content="Webmaster27">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <link href="{% static 'layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all"> -->
<link href="{% static 'favicon.ico' %}" rel="icon" type="image/x-icon" />
<script>

		addEventListener("load", function () {

			setTimeout(hideURLbar, 0);

		}, false);



		function hideURLbar() {

			window.scrollTo(0, 1);

		}

	</script>

	<!--// Meta tag Keywords -->

	<!-- css files -->

    <link rel="stylesheet" href="{% static 'css/age-verification.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Bootstrap-css -->

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<!-- Style-css -->

    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

	<!-- Font-Awesome-Icons-css -->

    <link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!-- Popup css (for Video Popup) -->

    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}" type="text/css" media="all">

	<!-- Lightbox css (for Projects) -->

    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />

	<!-- Flexslider css (for Testimonials) -->

	<!-- //css files -->

	<!-- web-fonts -->

	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">

	<!-- //web-fonts -->

</head>
<body>

<div class="">
    <div class="navbar navbar-inverse menu navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand brand" href="{% url 'encyclopedia:index' %}">
                    <img class="nav-icon" alt="Brand"
                    srcset="
                    {% static 'images/enofca-logo.jpg' %}">
                </a>
            </div>
            <div class="collapse navbar-collapse collapse" id="main-menu">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'encyclopedia:strain-list' %}">Strains</a> </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cannabis History<span class="caret"></span></a>
                        <ul class="dropdown-menu navbar-inverse full-width">
                            <li class="menu-list"><a class="menu-list-text" href="{% url 'encyclopedia:history' %}">Facts</a> </li>
                            <li class="menu-list"><a class="menu-list-text" href="{% url 'encyclopedia:cups' %}">Cups</a> </li>
                            <li class="menu-list"><a class="menu-list-text" href="{% url 'encyclopedia:seed_banks' %}">Seed banks</a> </li>
                        </ul>
                    </li>
                    <li><a href="{% url 'canna_cross:cross' %}">Canna Cross</a></li>
                    <li><a href="{% url 'orders:order' %}">Email Orders</a></li>
                    <li><a href="https://enofca0.webnode.cz/en/" target="_blank">Eshop</a></li>
                </ul>
            </div>

        </div>
    </div>


            {% block content %}

            {% endblock %}

	<!-- footer -->

	<div class="footer-bot">

		<div class="w3layouts-newsletter">

			<div class="w3ls-social-icons-2 col-xs-5">

				<h3>Social Media</h3>

				<a href="https://www.facebook.com/enofca/" title="Facebook ENofCA" target="_blank" class="facebook">

					<i class="fa fa-facebook"></i>

				</a>

				<a href="https://www.youtube.com/channel/UC3kVHCMgAvzVks0QAAuixwA" title="Youtube" target="_blank" class="youtube">

					<i class="fa fa-youtube"></i>

				</a>

				<a href="https://twitter.com/ENofCA" title="Twitter" target="_blank" class="Twitter">

					<i class="fa fa-twitter"></i>

				</a>

				<a href="https://www.instagram.com/_enofca/" title="Instagram" target="_blank" class="instagram">

					<i class="fa fa-instagram"></i>

				</a>

			</div>
			<div class="col-xs-7 ftr-menu">

				<ul>

					<li>

                        <a href="{% url 'encyclopedia:index' %}">Home</a>

					</li>

					<li>

						<a class="scroll" href="#about">About</a>

					</li>

					<li>

						<a class="scroll" href="#contact">Contact Us</a>

					</li>

					<li>

                        <a class="scroll" href="{% static 'documents/Announcement.pdf' %}">Announcement</a>

					</li>
				</ul>

			</div>

			<!-- <div class="col-md-7 agileinfo-newsletter"> -->

			<!-- 	<h3> -->

			<!-- 		<i class="fa fa-envelope" aria-hidden="true"></i>Newsletter</h3> -->

			<!-- 	<form action="#" method="post"> -->

			<!-- 		<input type="email" placeholder="Enter Your Email" name="email" required> -->

			<!-- 		<input type="submit" value="Subscribe"> -->

			<!-- 	</form> -->

			<!-- </div> -->

			<!-- <div class="clearfix"> </div> -->

		</div>

		<div class="container">

			<!-- <div class="col-xs-3 logo2"> -->

			<!-- 	<h2> -->

			<!-- 		<a href="index.html"> -->

			<!-- 			<span>En</span>cyclopedia -->

			<!-- 			<span>of  Ca</span>nnabis</a> -->

			<!-- 	</h2> -->

			<!-- </div> -->


			<div class="clearfix"></div>

			<div class="copy-right">

				<p> &copy; 2018 Encyclopedia of Cannabis. All Rights Reserved | Design by

					<a href="http://w3layouts.com/"> W3layouts</a>

				</p>

			</div>

		</div>

	</div>

	<!-- //footer -->
	<!-- jquery -->

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
	<!-- //jquery -->



    <script src="{% static 'js/bootstrap.js' %}"></script>

	<!-- Necessary-JavaScript-File-For-Bootstrap -->



	<!--  light box js -->

    <script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>

	<!-- //light box js-->



	<!-- stats numscroller-js-file -->

    <script src="{% static 'js/numscroller-1.0.js' %}"></script>

	<!-- //stats numscroller-js-file -->

	<!-- navigation -->

	<script>


			// Menu Functions

        $(document).ready(function () {
        });

	</script>

	<!-- //navigation -->



	<!-- pop-up(for video popup)-->

    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

	<script>

		$(document).ready(function () {

			$('.popup-with-zoom-anim').magnificPopup({

				type: 'inline',

				fixedContentPos: false,

				fixedBgPos: true,

				overflowY: 'auto',

				closeBtnInside: true,

				preloader: false,

				midClick: true,

				removalDelay: 300,

				mainClass: 'my-mfp-zoom-in'

			});



		});

	</script>

	<!-- //pop-up-box (syllabus section video)-->



	<!-- video js (background) -->

    <script src="{% static 'js/jquery.vide.min.js' %}"></script>

	<!-- //video js (background) -->



	<!-- smoothscroll -->

    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>

	<!-- //smoothscroll -->



	<!-- password-script -->

	<script>

		window.onload = function () {

			document.getElementById("password1").onchange = validatePassword;

			document.getElementById("password2").onchange = validatePassword;

		}



		function validatePassword() {

			var pass2 = document.getElementById("password2").value;

			var pass1 = document.getElementById("password1").value;

			if (pass1 != pass2)

				document.getElementById("password2").setCustomValidity("Passwords Don't Match");

			else

				document.getElementById("password2").setCustomValidity('');

			//empty string means no validation error

		}

	</script>

	<!-- //password-script -->



	<!-- start-smooth-scrolling -->

    <script src="{% static 'js/move-top.js' %}"></script>

    <script src="{% static 'js/easing.js' %}"></script>

	<script>

		jQuery(document).ready(function ($) {

			$(".scroll").click(function (event) {

				event.preventDefault();



				$('html,body').animate({

					scrollTop: $(this.hash).offset().top

				}, 1000);

			});

		});

	</script>

	<!-- //end-smooth-scrolling -->



	<!-- smooth scrolling-bottom-to-top -->

	<script>

		$(document).ready(function () {

			/*

				var defaults = {

				containerID: 'toTop', // fading element id

				containerHoverID: 'toTopHover', // fading element hover id

				scrollSpeed: 1200,

				easingType: 'linear'

				};

			*/

			$().UItoTop({

				easingType: 'easeOutQuart'

			});

		});

	</script>

	<a href="#" id="toTop" style="display: block;">

		<span id="toTopHover" style="opacity: 1;"> </span>

	</a>

	<!-- //smooth scrolling-bottom-to-top -->



	<!-- flexSlider (for testimonials) -->

    <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>

	<script>

		$(window).load(function () {

			$('.flexslider').flexslider({

				animation: "slide",

				start: function (slider) {

					$('body').removeClass('loading');

				}

			});

		});

	</script>

	<!-- //flexSlider (for testimonials) -->



	<!-- //js-scripts -->
    <script defer src="{% static 'js/age-verification.js' %}"></script>

    {% block scripts %}
    {% endblock %}
</body>

    {% block head %}
    {% endblock %}
</html>

encyclopedia/templates/canna_cross.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle"><span>C</span>anna Cross</h3>
            <div class="tittle-style"></div>
           <h3 align="center">
               <a class="choices-link" href="{% url 'canna_cross:list' 'paper' %}">Paper</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'cbd_oil' %}">CBD oil</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'homes' %}">Homes/Build/Fuel</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'clothing' %}">Clothing</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'medicine_food' %}">Medicine/Food</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'science' %}">Science</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'shops' %}">Shops</a>
               <a class="choices-link" href="{% url 'canna_cross:list' 'info_magazine' %}">Info/Magazine</a>
           </h3>
        </div>
        <div class="row" align="center">
            <img src="{% static 'images/hvezda.jpg' %}" class="img-responsive" alt="canna cross" />
        </div>
    </div>
</div>
{% endblock %}

encyclopedia/templates/order_info_mail.html
New order from enofca,<br>
id: {{order.id}}<br>
quantity: {{order.quantity}}<br>
client email: {{client.email}}<br>
first name: {{client.first_name}}<br>
last name: {{client.last_name}}<br>
phone: {{client.phone}}<br>
street: {{address.street}}<br>
street2: {{address.street2}}<br>
city: {{address.city}}<br>
region: {{address.region}}<br>
zip code: {{address.zip_code}}<br>
country: {{address.country}}<br>

encyclopedia/templates/order_mail.html
Dear customer,<br>
Thank you for your order ({{order}}). We have to calculate right shipping fee depending on your location. We
will respond as soon as possible generally within a few hours.<br>
Greenest Regards,<br>
Team ENOFCA