encyclopedia/urls.py
from django.conf.urls import url

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'strains/$', views.StrainListView.as_view(), name="strain-list"),
    url(r'history/$', views.HistoryListView.as_view(), name='history'),
    url(r'cups/$', views.CupListView.as_view(), name='cups'),
    url(r'seed-banks/$', views.SeedBankListView.as_view(), name='seed_banks'),
    url(r'strains/(?P<webId>[0-9]+)/$', views.StrainDeatailView.as_view(), name="strain"),
    url(r'history/(?P<pk>[0-9]+)/$', views.HistoryDetailView.as_view(), name="history_detail"),
    url(r'cup/(?P<pk>[0-9]+)/$', views.CupDetailView.as_view(), name="cup_detail"),
    url(r'seed-bank/(?P<pk>[0-9]+)/$', views.SeedBankDetailView.as_view(), name="seed_bank"),
    url(r'seed-banks/$', views.SeedBankListView.as_view(), name="seed_banks")
]

enofca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('encyclopedia.urls', namespace="encyclopedia")),
    url(r'^canna_cross/', include('canna_cross.urls', namespace="canna_cross")),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^order/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.

class Strain(models.Model):
    name = models.CharField(u'název', max_length=100)
    info = models.TextField(u'informace', blank=True)
    bank = models.ForeignKey('SeedBank', on_delete=models.SET_NULL, null=True, blank=True)
    cup = models.ManyToManyField('Cup', blank=True)
    cup_place = models.PositiveSmallIntegerField(blank=True, null=True, default=None)
    webId = models.SlugField(max_length=50, unique=True)
    link = models.URLField(blank=True, null=True)

    #medical
    stress = models.PositiveSmallIntegerField(blank=True, default=0)
    insomnia = models.PositiveSmallIntegerField(blank=True, default=0)
    pain = models.PositiveSmallIntegerField(blank=True, default=0)
    depression = models.PositiveSmallIntegerField(blank=True, default=0)
    headaches = models.PositiveSmallIntegerField(blank=True, default=0)
    lack_of_appetite = models.PositiveSmallIntegerField(blank=True, default=0)
    muscle_spams = models.PositiveSmallIntegerField(blank=True, default=0)
    nausea = models.PositiveSmallIntegerField(blank=True, default=0)
    cramps = models.PositiveSmallIntegerField(blank=True, default=0)
    fatigue = models.PositiveSmallIntegerField(blank=True, default=0)
    inflammation = models.PositiveSmallIntegerField(blank=True, default=0)

    #effects
    communicative = models.PositiveSmallIntegerField(blank=True, default=0)
    creative = models.PositiveSmallIntegerField(blank=True, default=0)
    energetic = models.PositiveSmallIntegerField(blank=True, default=0)
    euphoric = models.PositiveSmallIntegerField(blank=True, default=0)
    focused = models.PositiveSmallIntegerField(blank=True, default=0)
    happy = models.PositiveSmallIntegerField(blank=True, default=0)
    relaxed = models.PositiveSmallIntegerField(blank=True, default=0)
    uplifted = models.PositiveSmallIntegerField(blank=True, default=0)
    talkative = models.PositiveSmallIntegerField(blank=True, default=0)
    aroused = models.PositiveSmallIntegerField(blank=True, default=0)
    giggly = models.PositiveSmallIntegerField(blank=True, default=0)

    #negatives
    dry_eyes = models.PositiveSmallIntegerField(blank=True, default=0)
    dry_mouth = models.PositiveSmallIntegerField(blank=True, default=0)
    headache = models.PositiveSmallIntegerField(blank=True, default=0)
    paranoid = models.PositiveSmallIntegerField(blank=True, default=0)
    dizzy = models.PositiveSmallIntegerField(blank=True, default=0)
    anxious = models.PositiveSmallIntegerField(blank=True, default=0)


    def __str__(self):
        return '{} - {}'.format(self.name, self.webId)

def seed_bank_upload(instance, filename):
    return 'banks/{0}/{1}'.format(instance.name, filename)

class SeedBank(models.Model):
    logo = models.ImageField(upload_to=seed_bank_upload, blank=True, null=True)
    name = models.CharField(max_length=100)
    link = models.URLField(blank=True, null=True)
    info = models.TextField(u'informace', blank=True)

    def __str__(self):
        return '{}'.format(self.name)

#odstarnit poté z migrací
def revard_upload(instance, filename):
    return 'revards/{0}/{1}'.format(instance.name, filename)

def cup_upload(instance, filename):
    return 'cups/{0}/{1}'.format(instance.cup.name, filename)

class Revadr(models.Model):
    pass

class Cup(models.Model):
    name = models.CharField(max_length=100)
    info = models.TextField(u'informace', blank=True)

    def __str__(self):
        return '{}'.format(self.name)

class CupPhoto(models.Model):
    cup = models.ForeignKey('Cup', on_delete=models.SET_NULL, null=True, blank=True)
    logo = models.ImageField(upload_to=cup_upload, blank=True, null=True)
    for_place = models.PositiveSmallIntegerField(blank=True, default=0)

def strain_directory_upload(instance, filename):
    return 'strains/{0}/{1}'.format(instance.strain.name, filename)

class StrainPhoto(models.Model):
    photo = models.ImageField(upload_to=strain_directory_upload)
    strain = models.ForeignKey('Strain', on_delete=models.SET_NULL, null=True, blank=True)

HISTORY_CHOICES = (
    ('1900', 'before 1900'),
    ('2000', '1900 - 2000'),
    ('now', '2000 - now'),
)

def history_upload_to(instance, filename):
    return 'history/{0}/{1}'.format(instance.period, filename)

class History(models.Model):
    period = models.CharField(max_length=10, choices = HISTORY_CHOICES)
    header = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to=history_upload_to, blank=True, null=True)
    pdf = models.FileField(upload_to=history_upload_to, blank=True, null=True)
    standing = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{} - {}'.format(self.period, self.header)

def person_upload_to(instance, filename):
    return 'person/{0}/{1}'.format(instance.id, filename)

class Person(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to=person_upload_to, blank=True, null=True)
    pdf = models.FileField(upload_to=history_upload_to, blank=True, null=True)
    standing = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{}'.format(self.name)

encyclopedia/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView

from .models import Strain, StrainPhoto, History, HISTORY_CHOICES, CupPhoto, Cup, SeedBank
import pydash

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class StrainListView(ListView):
    model = Strain

    def get_context_data(self, **kwargs):
        strains = Strain.objects.order_by('name').values('name', 'webId')
        strains = pydash.group_by(strains, lambda strain: strain['name'][0].lower() if strain['name'][0].isalpha() else '#')
        kwargs['strains'] = sorted(strains.items())
        return super(StrainListView, self).get_context_data(**kwargs)

class StrainDeatailView(DetailView):
    model = Strain
    slug_field = "webId"
    slug_url_kwarg = "webId"
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super(StrainDeatailView, self).get_context_data(**kwargs)
        strain = self.get_object()
        context['photos'] = StrainPhoto.objects.filter(strain=strain)
        context['cups'] = CupPhoto.objects.filter(cup__in=strain.cup.all(), for_place=strain.cup_place)
        return context

class HistoryListView(ListView):
    model = History

    def get_context_data(self, **kwargs):
        historys = History.objects.order_by('standing')
        kwargs['historys'] = pydash.group_by(historys, lambda history: history.get_period_display())
        return super(HistoryListView, self).get_context_data(**kwargs)

class HistoryDetailView(DetailView):
    model = History

class CupListView(ListView):
    model = Cup

    def get_queryset(self):
        return Cup.objects.all().order_by('name')

class CupDetailView(DetailView):
    model = Cup

class SeedBankListView(ListView):
    model = SeedBank

    def get_queryset(self):
        return SeedBank.objects.all().order_by('name')

class SeedBankDetailView(DetailView):
    model = SeedBank

encyclopedia/templates/encyclopedia/cup_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle">Cup history </h3>
            <div class="tittle-style"></div>

           <h3 align="center">
               {{cup.name|upper}}
           </h3>

        </div>
            <h4 class="tittle" id="{{key}}"> {{key|upper}} </h4>
            <div class="history">
                    <div class="row">
                        <div class="history"> {{cup.info|safe}} </div>
                    </div>
                    <hr>
            </div>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/cup_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle">Cups history</h3>
            <div class="tittle-style"></div>

        </div>
            {% for cup in object_list %}
            <h4 class="tittle"> <a class="strains-link" href="{% url 'encyclopedia:cup_detail' pk=cup.pk %}"> {{cup.name|upper}} </a></h4>

            <!-- <div class="history"> -->
            <!--         <div class="row"> -->
            <!--             <div class="history"> {{cup.info|safe}} </div> -->
            <!--         </div> -->
            <!--         <hr> -->
            <!-- </div> -->
            {% endfor %}
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/history_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle"> <span>C</span>annabis history</h3>
            <div class="tittle-style"></div>

           <h3 align="center">
               {% for key, val in historys.items %}
                       <a class="choices-link" href="#{{key}}"> {{key|upper}} </a>
               {% endfor %}
           </h3>

        </div>
            <h4 class="tittle" id="{{key}}"> {{key|upper}} </h4>
            <div class="history">
                    <div class="row">
                        <h5 class="tittle"> {{history.header|upper}} </h5>
                        <div class="history col-sm-8"> {{history.text|safe}} </div>
                        {% if history.image %}
                            <div class="col-sm-4 history-image">
                                <a href="{{history.image.url}}" data-lightbox="example-set">
                                    <img src="{{history.image.url}}" alt="{{history.header}}" class="img-responsive">
                                 </a>
                            </div>
                        {% endif %}
                    </div>
                    <hr>
                    {% if history.pdf %}
                        <div class="row history-pdf">
                            <p>
                                <b>Download:</b>
                                <a href="{{history.pdf.url}}">
                                    PDF
                                </a>
                            </p>
                        </div>
                        <hr>
                    {% endif %}
            </div>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/history_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle"> <span>C</span>annabis history</h3>
            <div class="tittle-style"></div>

           <h3 align="center">
               {% for key, val in historys.items %}
                       <a class="choices-link" href="#{{key}}"> {{key|upper}} </a>
               {% endfor %}
           </h3>

        </div>
            {% for key, values in historys.items %}
            <h4 class="tittle" id="{{key}}"> {{key|upper}} </h4>
            <div class="history">
                {% for history in values %}
                    <div class="row">
                        <h5 class="tittle"> <a class="strains-link" href="{% url 'encyclopedia:history_detail' pk=history.pk %}"> {{history.header|upper}} </a></h5>
                        <div class="history col-sm-8"> {{history.short_info|safe}} </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
            {% endfor %}
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/seedbank_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle">{{seedbank.name|upper}}</h3>
            <div class="tittle-style"></div>

        </div>
            <div class="row" align="center">
                <div class="logo-image" align="center">
                    {% if seedbank.link %}
                        <a href="{{seedbank.link}}" target="_blank">
                            <image src="{{seedbank.logo.url}}">
                        </a>
                    {% else %}
                        <image src="{{seedbank.logo.url}}">
                    {% endif %}
                </div>
            </div>
            <div class="history">
                    <div class="row">
                        <div class="history"> {{seedbank.info|safe}} </div>
                    </div>
                    <hr>
            </div>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/seedbank_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle">Seed banks</h3>
            <div class="tittle-style"></div>

        </div>
            {% for cup in object_list %}
            <h4 class="tittle"> <a class="strains-link" href="{% url 'encyclopedia:seed_bank' pk=cup.pk %}"> {{cup.name|upper}} </a></h4>

            <!-- <div class="history"> -->
            <!--         <div class="row"> -->
            <!--             <div class="history"> {{cup.info|safe}} </div> -->
            <!--         </div> -->
            <!--         <hr> -->
            <!-- </div> -->
            {% endfor %}
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/strain_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<div class="banner-bottom-w3l">
    <div class="container">
        <div class="title-div">
            <h3 class="tittle"> <span>C</span>annabis strains in Alphabetical Order</h3>
            <div class="tittle-style"></div>
           <h3 class="choices" align="center">
               {% for key, value in strains %}
                       <a class="choices-link" href="#{{key}}"> {{key|upper}} </a>
               {% endfor %}
           </h3>

            {% for key, values in strains %}
            <h4 class="tittle" align="center" id="{{key}}"> {{key|upper}} </h4>
            <div>
                {% for strain in values %}
                    <a class="strains-link"  href="{% url 'encyclopedia:strain' webId=strain.webId %}"> {{strain.name}}</a>{% if not forloop.last %} | {% endif %}
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}